# Generated by Django 6.1.1 on 2026-09-06 12:31

import apps.profiles.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('google_scholar_url', models.URLField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=apps.profiles.models.profile_photo_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.profiles.models.profile_thumb_path)),
                ('photo_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('photo_updated_at', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('REGISTERED_USERS', 'Registered Users Only'), ('CONNECTIONS_ONLY', 'Connections Only'), ('PRIVATE', 'Private')], default='REGISTERED_USERS', max_length=25)),
                ('completion_percentage', models.IntegerField(default=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
