# Generated by Django 6.1.1 on 2026-09-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='candidate_match_threshold',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='digest_frequency',
            field=models.CharField(choices=[('INSTANT', 'Instant Alerts'), ('DAILY', 'Daily Digest'), ('WEEKLY', 'Weekly Summary'), ('OFF', 'Off')], default='WEEKLY', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_search_status',
            field=models.CharField(choices=[('ACTIVELY_LOOKING', 'Actively Looking for Opportunities'), ('OPEN', 'Open to Relevant Roles'), ('NOT_LOOKING', 'Not Looking Currently')], default='ACTIVELY_LOOKING', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mentorship_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_theme',
            field=models.CharField(default='LIGHT', max_length=20),
        ),
    ]
