# Generated by Django 6.1.1 on 2026-09-06 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('official_name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('institution_type', models.CharField(choices=[('UNIVERSITY', 'University'), ('COLLEGE', 'College'), ('INSTITUTE', 'Institute'), ('TECHNICAL_INSTITUTE', 'Technical Institute'), ('MEDICAL_INSTITUTE', 'Medical Institute'), ('BUSINESS_SCHOOL', 'Business School'), ('LAW_SCHOOL', 'Law School'), ('RESEARCH_CENTRE', 'Research Centre'), ('POLYTECHNIC', 'Polytechnic'), ('OPEN_UNIVERSITY', 'Open University'), ('VOCATIONAL_INSTITUTE', 'Vocational Institute')], default='UNIVERSITY', max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institutions/logos/')),
                ('country', models.CharField(default='India', max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('aishe_code', models.CharField(blank=True, max_length=50, null=True)),
                ('ugc_recognized', models.BooleanField(default=True)),
                ('naac_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('nirf_rank', models.IntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('official_apply_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('head_of_department', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.field')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='institutions.institution')),
            ],
            options={
                'unique_together': {('institution', 'name')},
            },
        ),
    ]
