# Generated by Django 6.1.1 on 2026-09-06 12:31

import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('primary_role', models.CharField(choices=[('STUDENT', 'Student'), ('ACADEMICIAN', 'Academician'), ('INDUSTRY', 'Industry'), ('INSTITUTION', 'Institution'), ('SYSTEM_ADMIN', 'System Administrator')], default='STUDENT', max_length=30)),
                ('sub_role', models.CharField(choices=[('STUDENT_GENERAL', 'Student'), ('FACULTY', 'Faculty'), ('PROFESSOR', 'Professor'), ('RESEARCHER', 'Researcher'), ('FACULTY_MENTOR', 'Faculty Mentor'), ('ACADEMIC_DEPT_COORD', 'Department Coordinator'), ('ACADEMIC_RESEARCH_COORD', 'Research Coordinator'), ('COMPANY_ADMIN', 'Company Admin'), ('HR', 'HR Manager'), ('RECRUITER', 'Recruiter'), ('INDUSTRY_MENTOR', 'Industry Mentor'), ('INDUSTRY_EXPERT', 'Industry Expert'), ('TRAINING_COORD', 'Training Coordinator'), ('INDUSTRY_RESEARCH_COORD', 'Industry Research Coordinator'), ('INSTITUTION_ADMIN', 'Institution Admin'), ('PRINCIPAL', 'Principal'), ('DIRECTOR', 'Director'), ('HOD', 'Head of Department (HOD)'), ('TPO', 'Training & Placement Officer (TPO)'), ('PLACEMENT_OFFICER', 'Placement Officer'), ('INST_DEPT_COORD', 'Department Coordinator'), ('SKILL_COORD', 'Skill Coordinator'), ('INST_RESEARCH_COORD', 'Research Coordinator')], default='STUDENT_GENERAL', max_length=40)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
