# Generated by Django 6.1.1 on 2026-09-06 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('opportunity_type', models.CharField(choices=[('JOB', 'Job'), ('INTERNSHIP', 'Internship'), ('APPRENTICESHIP', 'Apprenticeship'), ('FELLOWSHIP', 'Fellowship'), ('SCHOLARSHIP', 'Scholarship'), ('PROJECT', 'Industry Project')], default='JOB', max_length=30)),
                ('country', models.CharField(default='India', max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('mode', models.CharField(choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ON_SITE', 'On-Site')], default='HYBRID', max_length=20)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('eligibility', models.TextField(blank=True, null=True)),
                ('stipend_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('salary_period', models.CharField(default='Monthly', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('official_apply_url', models.URLField()),
                ('is_verified', models.BooleanField(default=True)),
                ('verification_source', models.CharField(default='Official Portal', max_length=150)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='taxonomy.field')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='opportunities', to='skills.skill')),
                ('subfield', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.subfield')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
