# Generated by Django 6.1.1 on 2026-09-06 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('GOVERNMENT', 'Government Statutory Body (e.g. AISHE, UGC, AICTE)'), ('REGULATORY', 'Regulatory Authority'), ('UNIVERSITY', 'University Official Portal'), ('COLLEGE', 'College Official Portal'), ('COMPANY', 'Official Enterprise Portal'), ('VERIFIED_PROVIDER', 'Verified Course / Certification Provider')], default='UNIVERSITY', max_length=40)),
                ('base_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('source_a_name', models.CharField(max_length=150)),
                ('source_a_value', models.TextField()),
                ('source_b_name', models.CharField(max_length=150)),
                ('source_b_value', models.TextField()),
                ('resolved_value', models.TextField(blank=True, null=True)),
                ('resolution_method', models.CharField(default='Authority Score', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=150, null=True)),
                ('original_url', models.URLField()),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified Record'), ('PENDING', 'Pending Verification'), ('CONFLICT', 'Source Conflict Detected'), ('BROKEN', 'Broken / Unreachable Source')], default='VERIFIED', max_length=20)),
                ('verified_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='sources.source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
