# Generated by Django 6.1.1 on 2026-09-06 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('provider', models.CharField(help_text='University, Coursera, NPTEL, edX, AIC Platform', max_length=150)),
                ('instructor', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField()),
                ('level_name', models.CharField(default='Intermediate', max_length=50)),
                ('duration_hours', models.IntegerField(default=40)),
                ('mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'On-Campus / Offline'), ('HYBRID', 'Hybrid')], default='ONLINE', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('provides_certificate', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=4.5)),
                ('enrolled_count', models.IntegerField(default=0)),
                ('official_url', models.URLField()),
                ('is_verified', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='taxonomy.field')),
                ('subfield', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.subfield')),
            ],
            options={
                'ordering': ['-rating', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='education.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('programme_type', models.CharField(choices=[('DEGREE', 'Degree'), ('DIPLOMA', 'Diploma'), ('CERTIFICATE', 'Certificate'), ('BOOTCAMP', 'Bootcamp'), ('FELLOWSHIP', 'Fellowship'), ('RESEARCH_PROGRAMME', 'Research Programme'), ('EXCHANGE_PROGRAMME', 'Exchange Programme'), ('EXECUTIVE_EDUCATION', 'Executive Education')], default='DEGREE', max_length=40)),
                ('description', models.TextField()),
                ('learning_outcomes', models.TextField(blank=True, null=True)),
                ('eligibility', models.TextField(blank=True, null=True)),
                ('duration_months', models.IntegerField(default=24)),
                ('credits', models.IntegerField(default=120)),
                ('mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'On-Campus / Offline'), ('HYBRID', 'Hybrid')], default='OFFLINE', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('has_scholarship', models.BooleanField(default=False)),
                ('stipend_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('official_url', models.URLField()),
                ('is_verified', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.department')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='taxonomy.field')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='institutions.institution')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.educationlevel')),
                ('subfield', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.subfield')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
