# Generated by Django 6.1.1 on 2026-09-06 13:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('skills', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('issuing_organization', models.CharField(help_text='e.g. AWS, Google Cloud, Microsoft, Cisco, NPTEL', max_length=255)),
                ('credential_code', models.CharField(blank=True, help_text='e.g. SAA-C03, AZ-900, CKA, CISSP', max_length=100, null=True)),
                ('level', models.CharField(choices=[('FOUNDATIONAL', 'Foundational / Entry'), ('ASSOCIATE', 'Associate'), ('PROFESSIONAL', 'Professional'), ('SPECIALTY', 'Specialty / Expert')], default='ASSOCIATE', max_length=30)),
                ('description', models.TextField()),
                ('exam_format', models.CharField(default='Online Proctored / Authorized Test Center', max_length=150)),
                ('duration_minutes', models.IntegerField(default=120)),
                ('validity_years', models.IntegerField(default=3)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('official_verify_url', models.URLField(help_text='Official exam registration or certificate verification portal')),
                ('is_verified', models.BooleanField(default=True)),
                ('verification_source', models.CharField(default='Official Issuing Body', max_length=150)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='taxonomy.field')),
                ('skills_covered', models.ManyToManyField(blank=True, related_name='certifications', to='skills.skill')),
                ('subfield', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.subfield')),
            ],
            options={
                'ordering': ['issuing_organization', 'title'],
            },
        ),
    ]
