# Generated by Django 6.1.1 on 2026-09-08 20:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_certification'),
        ('institutions', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('event_type', models.CharField(choices=[('CONFERENCE', 'Conference'), ('WORKSHOP', 'Workshop'), ('SEMINAR', 'Seminar'), ('HACKATHON', 'Hackathon'), ('WEBINAR', 'Webinar'), ('FDP', 'Faculty Development Programme (FDP)'), ('SYMPOSIUM', 'Symposium'), ('BOOTCAMP', 'Bootcamp'), ('PANEL', 'Panel Discussion'), ('EXPO', 'Tech Expo / Industry Fair')], default='SEMINAR', max_length=30)),
                ('mode', models.CharField(choices=[('ONLINE', 'Online / Virtual'), ('OFFLINE', 'On-Campus / In-Person'), ('HYBRID', 'Hybrid')], default='HYBRID', max_length=20)),
                ('organizer_name', models.CharField(help_text='e.g. IIT Bombay CSE Dept, NASSCOM, Google India', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, help_text='e.g. Seminar Hall A, VMCC Building, IIT Bombay', max_length=255, null=True)),
                ('city', models.CharField(default='Bengaluru', max_length=100)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('online_platform', models.CharField(blank=True, help_text='e.g. Google Meet, Zoom, MS Teams', max_length=150, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('speakers', models.TextField(blank=True, help_text='Comma-separated speaker names and titles', null=True)),
                ('topics_covered', models.TextField(blank=True, help_text='Comma-separated key topics', null=True)),
                ('target_audience', models.CharField(default='Students, Faculty, Researchers', max_length=255)),
                ('prerequisites', models.TextField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, help_text='What attendees will gain', null=True)),
                ('max_registrations', models.IntegerField(default=200)),
                ('is_free', models.BooleanField(default=True)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('provides_certificate', models.BooleanField(default=True)),
                ('official_url', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.department')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.field')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution')),
            ],
            options={
                'ordering': ['start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_attended', models.BooleanField(default=False)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='education.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('event', 'student')},
            },
        ),
    ]
