# Generated by Django 6.1.1 on 2026-09-09 05:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('REGISTERED', 'Registered'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('EVALUATED', 'Evaluated'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview Scheduled'), ('INTERNSHIP', 'Internship Offered'), ('JOB_OFFER', 'Job Offer Extended'), ('REJECTED', 'Not Selected')], default='REGISTERED', max_length=20)),
                ('progress_pct', models.IntegerField(default=0, help_text='0-100 self-reported progress')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='IndustryChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('problem_statement', models.TextField()),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner (No prior experience needed)'), ('INTERMEDIATE', 'Intermediate (1–2 years exposure)'), ('ADVANCED', 'Advanced (3+ years / competitive)'), ('EXPERT', 'Expert (Research / Production grade)')], default='INTERMEDIATE', max_length=20)),
                ('duration_weeks', models.IntegerField(default=4)),
                ('team_min', models.IntegerField(default=1)),
                ('team_max', models.IntegerField(default=4)),
                ('deadline', models.DateTimeField()),
                ('evaluation_criteria', models.TextField(blank=True, help_text='JSON string: [{"name": "Technical", "weight": 40}, ...]', null=True)),
                ('rewards', models.TextField(blank=True, null=True)),
                ('opportunity_after', models.TextField(blank=True, help_text='What students can get after completing this challenge', null=True)),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open for Participation'), ('CLOSED', 'Submissions Closed'), ('EVALUATING', 'Under Evaluation'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20)),
                ('is_team_challenge', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=True)),
                ('max_participants', models.IntegerField(default=500)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_challenges', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='taxonomy.field')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('invite_code', models.CharField(max_length=12, unique=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='genome.industrychallenge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChallengeTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='genome.challengeparticipant')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='genome.industrychallenge')),
            ],
            options={
                'ordering': ['status', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('github_url', models.URLField(blank=True, null=True)),
                ('demo_url', models.URLField(blank=True, null=True)),
                ('documentation_url', models.URLField(blank=True, null=True)),
                ('presentation_url', models.URLField(blank=True, null=True)),
                ('is_final', models.BooleanField(default=False, help_text='True = final submission, no more edits allowed')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='genome.challengeparticipant')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='genome.challengeteam')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='genome.industrychallenge')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='genome.industrychallenge'),
        ),
        migrations.CreateModel(
            name='SkillNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('PROGRAMMING', 'Programming & Development'), ('DATA', 'Data & Analytics'), ('AI_ML', 'Artificial Intelligence & ML'), ('CLOUD', 'Cloud & DevOps'), ('CYBERSECURITY', 'Cybersecurity'), ('DESIGN', 'Design & UX'), ('BUSINESS', 'Business & Management'), ('CORE_ENG', 'Core Engineering'), ('BIOMEDICAL', 'Biomedical & Life Sciences'), ('LEGAL', 'Law & Governance'), ('AGRICULTURE', 'Agriculture & Environment'), ('GENERAL', 'General & Soft Skills')], default='PROGRAMMING', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='fa-solid fa-code', max_length=60)),
                ('order', models.IntegerField(default=0)),
                ('industry_demand_score', models.IntegerField(default=50, help_text='0-100 relative demand from industry job postings')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_nodes', to='taxonomy.field')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='genome.skillnode')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='skills.skill')),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_type', models.CharField(choices=[('SELF_DECLARED', 'Self Declared'), ('COURSE', 'Course Completed'), ('ASSESSMENT', 'Assessment Passed'), ('PROJECT', 'Project Submitted'), ('CERTIFICATION', 'Certification Earned'), ('INTERNSHIP', 'Internship Completed'), ('INDUSTRY_CHALLENGE', 'Industry Challenge'), ('FACULTY_VERIFIED', 'Faculty Verified'), ('COMPANY_VERIFIED', 'Company Verified'), ('EVENT_WORKSHOP', 'Workshop / Event Attended'), ('LAB_PRACTICAL', 'Lab / Practical Work')], default='SELF_DECLARED', max_length=30)),
                ('source_title', models.CharField(help_text='e.g. "Python Fundamentals — NPTEL", "AI Challenge #1024"', max_length=255)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('score_percentage', models.IntegerField(default=0, help_text='Score if applicable (0 if not)')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='True only if a faculty/company/admin explicitly approved this')),
                ('notes', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evidences', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_given', to=settings.AUTH_USER_MODEL)),
                ('skill_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='genome.skillnode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillDemandSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demand_score', models.IntegerField(default=0, help_text='Number of open requirements weighted by importance')),
                ('source', models.CharField(choices=[('PORTAL_JOBS', 'Portal Job Postings'), ('PORTAL_INTERNSHIPS', 'Portal Internship Postings'), ('PORTAL_CHALLENGES', 'Industry Challenges'), ('EMPLOYER_SURVEY', 'Employer Survey'), ('IMPORTED', 'Imported External Data')], default='PORTAL_JOBS', max_length=30)),
                ('snapshot_date', models.DateField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_snapshots', to='genome.skillnode')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.AddField(
            model_name='industrychallenge',
            name='preferred_skills',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_challenges', to='genome.skillnode'),
        ),
        migrations.AddField(
            model_name='industrychallenge',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='required_by_challenges', to='genome.skillnode'),
        ),
        migrations.CreateModel(
            name='SkillSupplySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_students', models.IntegerField(default=0)),
                ('verified_count', models.IntegerField(default=0)),
                ('intermediate_plus_count', models.IntegerField(default=0)),
                ('snapshot_date', models.DateField(auto_now_add=True)),
                ('skill_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_snapshots', to='genome.skillnode')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technical_score', models.IntegerField(default=0, help_text='0-100')),
                ('problem_score', models.IntegerField(default=0, help_text='0-100')),
                ('innovation_score', models.IntegerField(default=0, help_text='0-100')),
                ('implementation_score', models.IntegerField(default=0, help_text='0-100')),
                ('documentation_score', models.IntegerField(default=0, help_text='0-100')),
                ('presentation_score', models.IntegerField(default=0, help_text='0-100')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_given', to=settings.AUTH_USER_MODEL)),
                ('skills_verified', models.ManyToManyField(blank=True, related_name='verified_by_evaluations', to='genome.skillnode')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='genome.challengesubmission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChallengeTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='genome.challengeteam')),
            ],
            options={
                'unique_together': {('team', 'student')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='challengeparticipant',
            unique_together={('challenge', 'student')},
        ),
        migrations.CreateModel(
            name='StudentSkillProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proficiency', models.CharField(choices=[('BEGINNER', 'Beginner'), ('ELEMENTARY', 'Elementary'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=20)),
                ('score', models.IntegerField(default=0, help_text='0-100 numerical proficiency score')),
                ('confidence_score', models.IntegerField(default=0, help_text='0-100 computed confidence based on evidence weights')),
                ('evidence_count', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False, help_text='True if at least one approved non-self-declared evidence exists')),
                ('target_proficiency', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('ELEMENTARY', 'Elementary'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], max_length=20, null=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('skill_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_profiles', to='genome.skillnode')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genome_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['skill_node__category', 'skill_node__order'],
                'unique_together': {('student', 'skill_node')},
            },
        ),
    ]
