# Generated by Django 6.1.1 on 2026-09-06 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('isced_level', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical'), ('NATURAL_SCIENCES', 'Natural Sciences'), ('MEDICAL_HEALTH', 'Medical & Health'), ('BUSINESS_MANAGEMENT', 'Business & Management'), ('ARTS_HUMANITIES', 'Arts & Humanities'), ('LAW', 'Law'), ('EDUCATION', 'Education'), ('SOCIAL_SCIENCES', 'Social Sciences'), ('DESIGN_CREATIVE', 'Design & Creative'), ('AGRICULTURE_FOOD', 'Agriculture & Food'), ('ENVIRONMENT_SUSTAINABILITY', 'Environment & Sustainability'), ('MEDIA_COMMUNICATION', 'Media & Communication'), ('SPORTS', 'Sports'), ('VOCATIONAL_SKILLED', 'Vocational & Skilled Trades'), ('INTERDISCIPLINARY', 'Interdisciplinary')], default='TECHNICAL', max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='academic-cap', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subfield',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfields', to='taxonomy.field')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('field', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('subfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='taxonomy.subfield')),
            ],
            options={
                'unique_together': {('subfield', 'slug')},
            },
        ),
    ]
